### ISSUE TITLE
when a link starts a timeline, it seems to start all timelines not just the one referenced

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#108]
@wphicks This may also be a more general problem since students have noticed that click directed at object with an enabled link also trigger objects (perhaps "in-line" with the click, perhaps not) whose links are *not* enabled.

Observe the effects in the 'sample_17_rotation.xml' recently pushed to the samples_debugging branch of w3d_samples.

**Comment by wphicks** [comment]
Oof, that's a nasty one. I'll see what I can figure out.

**Comment by shadoof** [comment]
@wphicks HI Will, I think this is a big and important one. Meredith (good student) encountered effects today and I think that this should be top priority. (Know you're busy; hope you're coping/do well.)

**Comment by wphicks** [comment]
Mostly note to self: That sample references non-existent timeline rot_guan. Probably unrelated but should be fixed.

**Comment by wphicks** [comment]
Thankfully, I'm not seeing any evidence that this goes beyond the issues with clicking (#71). An earlier attempt at fixing this accidentally disrupted the ability to disable links. I'll fix that and then put #71 at the top of my list. @shadoof, the sample that you pointed to seems to be on the fritz for unrelated reasons (which I should probably look into as well). If you have another sample that cleanly illustrates the behavior we're worried about, it would be much appreciated.

**Comment by wphicks** [comment]
It's late, and I'm having trouble finding the enable/disable issue. I'll tackle this first thing on Thursday.

**Comment by shadoof** [comment]
@wphicks I tidied samples_17_rotation and there aren't references to non-existent timelines. The problem of a link that is only suppose to start on timeline (rot_guan_1) also starting another timeline (col_guan) still exists.

Also the behavior of the col_guan timeline seems strange. It should fade the character back and forth from red to white, looping. (Behavior of col_guan timeline is different and 'as coded' in the old CW rendered.)

**Comment by shadoof** [comment]
@wphicks samples_25_timelinebug newly added to w3d_samples/samples_debugging demonstrates this minimally and clearly.

**Comment by wphicks** [comment]
Just confirmed that bbce03dba5004113c1dbce1d5c8919fdfb066e2c fixes this by testing against sample_25_timelinebug. If you continue to see issues with this problem, feel free to reopen. If you wouldn't mind opening a fresh issue for any problems that you're seeing with the timeline in sample_17_rotation, that would be great.

**Comment by shadoof** [comment]
I'm uncertain @wphicks about the best workflow for testing. I assumed:
* navigate to current installation (installed as for student users - I keep this separate from my own local forked development repo)
* git checkout develop
* git pull

Then use CWeditor in the dir above to run test samples. But on f0ebd8a in the develop branch I still see the unwanted behavior when I do this. Am I missing something?

**Comment by wphicks** [comment]
Oh dear- that should have worked. It's already in master, so you can just do a `git checkout master`, but that's not the issue (your commit SHA is correct). What exactly did you do to test?

**Comment by wphicks** [comment]
Oh darn! I see what's going on here... I'll get it fixed up in just a moment.

**Comment by wphicks** [comment]
@shadoof Fixed this with f79141b16be8272282552f774f5fb823ebdfb023. If you can confirm that this is working as intended, I'll build and push new zip installs.
